import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ClientAuthProvider from "@/components/ClientAuthProvider";
import Header from "@/components/ui/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <ClientAuthProvider > */}
          <Header />
        {/* </ClientAuthProvider > */}
        {children}
      </body>
    </html>
  );
}





// import Header from '@/components/ui/Header';
// import React from 'react';
// import "./globals.css";
// import LogoutButton from '@/components/ui/LogoutButton';

// function MainLayout({ children }) {
//   return (
//     <>
//       <html lang="en">
//         <body>
//           <Header />
//           <LogoutButton />
//           {children}
//         </body>
//       </html>
//     </>
//   );
// }

// export default MainLayout;